#!/bin/bash
:’Write a bash script that creates in the current directory a file named s1 . The file s1 contains a single line saying I am s1 . Then it creates a file named s1a. The file s1a contains a single line saying I am s1a . Then it creates a file named s2. The file s2 contains a single line saying I am s2 . Then it creates a file named s2a. The file s2a contains a single line saying I am s2a . Then it creates a file named s3. The file s3 contains a single line saying I am s3 . Then in a loop it tests which of the files s1, s1a, s2, s2a, and s3 exist in the current directory. It is achieved by having 5 variables x1,
x1a, x2, x2a, and x3 initialized to 0. Then the script goes through the list of files checking whether the file is one of the files s1, s1a, s2, s2a, and s3, and if so, the corresponding variable is set to 1. Then the script goes through the variables and based on their values, it displays a message like s1 not found in current directory or s1 found in current directory. Then all the variables are summed up and if the sum is smaller than 5, a message not all files found in current directory is displayed, otherwise a message all files found in current directory is displayed. After, the script removes only the created files and terminates.
‘




echo "I am s1" > s1
echo "I am s1a" > s1a
echo "I am s2" > s2
echo "I am s2a" > s2a
#echo "I am s3" > s3

x1=0
x1a=0
x2=0
x2a=0
x3=0
x4=0
Files=`ls`
for file in $Files
do
  if [ "$file" == "s1" ]     #so == and = is the same? and "" and no "" is same too?
  then
    x1=1
  fi
  if [ "$file" = "s1a" ]
  then
    x1a=1
  fi
  if [ "$file" = "s2" ]
  then
    x2=1
  fi
  if [ "$file" = "s2a" ]
  then
    x2a=1
  fi
  if [ "$file" = "s3" ]
  then
    x3=1
  fi
done

if [ $x1 -eq 1 ]   #equal to a number
then
  echo "s1 found in current directory"
else
  echo "s1 not found in current directory"
fi
if [ $x1a -eq 0 ]
then
  echo "s1a not found in current directory"
else
  echo "s1a found in current directory"
fi
if [ $x2 -eq 0 ]
then
  echo "s2 not found in current directory"
else
  echo "s2 found in current directory"
fi
if [ $x2a -eq 0 ]
then
  echo "s2a found in current directory"
else
  echo "s2a found in current directory"
fi
if [ $x3 -eq 0 ]
then
  echo "s3 not found in current directory"
else
  echo "s3 found in current directory"
fi

#x=$x1
x=$((x1+x1a))   #here $ the same
x=$((x+$x2))
x=$((x+$x2a))
x=$((x+$x3))

if [ $x -lt 5 ]     #-lt stands for less than
then
  echo "not all files found in current directory"
else
  echo "all files found in current directory"
fi

rm s[123]*   #[sth]the middle is 1/2/3
