#!/bin/bash

:’Create a bash script s2 that has four line arguments. It creates a file whose name is $2 from a file whose name is $1. It creates it by copying from $1 the lines that contain strings $3 or $4. The last line of the file $1 should say done. For instance, executing s2 hello test 1 3 will create a file named test containing all the lines from the file hello that contain 1 or 3 and a line done, or s2 hello test a bc will create a file named test containing all the lines from the file hello that contain a or bc and a line done.
‘


# check if th enumber of arguments is 4
if [ $# -ne 4 ] 
then
    echo "Usage: `basename $0` \$1 \$2 \$3 \$4" 
    exit
fi

#extract all the lines with $3 or $4 from $1 and create $2
grep "$3\|$4" $1 > $2

# explore some other possible forms 
#grep -E "$3|$4" $1 > $2
#grep -e $3 -e $4 $1 > $2
#egrep "$3|$4" $1 > $2    #egrep=grep -E


#final line
echo "done" >> $2
