#!/bin/bash

echo "Please enter three-letter code of the day of the week"
echo "examples: Mon, Tue, ..., Sun" 
read -p "" day
echo "++++++++++++++"

realdate=$(date)

if [ $day == ${realdate:0:3} ]
then
    echo "Good answer"
    echo "The day of the week is $day"
else
    echo "Bad answer"
    echo "your answer: $day, real day: ${realdate:0:3}"
fi
