#!/bin/bash

mkdir DIR1
echo "DIR1 created"
cd DIR1

mkdir DIR2
echo "DIR1/DIR2 created"
cd DIR2

echo "I am file X" > X

echo "contents of DIR2"
ls .

echo "contents of DIR1"
ls ..

echo "contents of current directory"
cd .. #back to DIR1
cd .. #back to current dir
ls .

mv DIR1/DIR2/X .
rmdir DIR1
rm DIR1
rm -r DIR1

ls .
